# Generated by Django 4.2.9 on 2024-02-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_comment',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
