# Generated by Django 4.2.9 on 2024-02-08 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_post_likes'),
        ('user', '0003_postlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='post.post'),
        ),
    ]
